name: Playwright Tests (Deploy)
on:
  deployment_status:
jobs:
  playwright_deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Run end-to-end tests
        run: HOME=/root pnpm exec playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 7
